---
bool ready
string failure_code
int64 observed_ns
int64 limit_ns
string detail
builtin_interfaces/Time observation_cutoff
sensor_msgs/Image camera_left
sensor_msgs/Image camera_overview
sensor_msgs/Image camera_right
arx5_collection_interfaces/ArmState left_arm
arx5_collection_interfaces/ArmState right_arm
