name: arx5-dual-bringup

services:
  device-bringup:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bringup
    image: arx5-dual-bringup:dev
    container_name: arx5-bringup-w3
    init: true
    privileged: true
    network_mode: host
    stop_grace_period: 5s
    volumes:
      - /run/udev:/run/udev:ro
      - ..:/workspace:ro
      - ../reports:/reports
