schema_version = 1

[output]
backend = "lerobot-v2.1"
repo_id = "local/uniqlo_fold_aux_v1"
path = "/mnt/pfs/swy/dataset/1011/arx5/uniqlo/lerobot/local/uniqlo_fold_aux_v1"

[[sources]]
name = "uniqlo_native"
path = "/mnt/pfs/swy/dataset/1011/arx5/uniqlo/lerobot/local/uniqlo_native_2026-08-27_2026-08-28"
select_all = true

[[sources]]
name = "fold_26_aux"
path = "/mnt/pfs/swy/dataset/1011/arx5/fold_cloth/lerobot/local/fold_cloth_2026-08-26_full-v1"
select_all = true
