schema_version = 1

[output]
backend = "lerobot-v2.1"
repo_id = "local/fold_hq_2026-08-26_2026-08-27"
path = "/mnt/pfs/swy/dataset/1011/arx5/fold_cloth/lerobot/local/fold_hq_2026-08-26_2026-08-27"

[[sources]]
name = "fold_26_full"
path = "/mnt/pfs/swy/dataset/1011/arx5/fold_cloth/lerobot/local/fold_cloth_2026-08-26_full-v1"
select_all = true

[[sources]]
name = "fold_27"
path = "/mnt/pfs/swy/dataset/1011/arx5/fold_cloth/lerobot/local/fold_cloth_2026-08-27"
select_all = true
